# Generated by Django 5.2.11 on 2026-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True)),
                ('contraseña_hasheada', models.CharField(max_length=64)),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
